<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\hip\\clirunner' => '/CliRunner.php',
                'theseer\\hip\\config' => '/Config.php',
                'theseer\\hip\\directory' => '/Directory.php',
                'theseer\\hip\\factory' => '/Factory.php',
                'theseer\\hip\\file' => '/File.php',
                'theseer\\hip\\fileglobiterator' => '/FileGlobIterator.php',
                'theseer\\hip\\importer' => '/Importer.php',
                'theseer\\hip\\processor' => '/Processor.php',
                'theseer\\hip\\request' => '/Request.php',
                'theseer\\hip\\version' => '/Version.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    true
);
// @codeCoverageIgnoreEnd
